apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
